// <auto-generated />
using System;
using MessageSender_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageSender_MVC.Migrations
{
    [DbContext(typeof(MessageSenderDbContext))]
    partial class MessageSenderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MessageSender_MVC.Domain.MobileContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoblieNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MobileContacts");
                });

            modelBuilder.Entity("MessageSender_MVC.Domain.MobileMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MobileContactId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MobileContactId");

                    b.ToTable("MoblieMessages");
                });

            modelBuilder.Entity("MessageSender_MVC.Domain.MobileMessage", b =>
                {
                    b.HasOne("MessageSender_MVC.Domain.MobileContact", "MobileContact")
                        .WithMany()
                        .HasForeignKey("MobileContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
